### ISSUE TITLE
Option to prevent comment stripping

### ISSUE THREAD

**Issue by rafis** [yocmen/html-minify#2]
Can you please add option in config to prevent [comment stripping](https://github.com/yocmen/html-minify/blob/751abd1e3b5cb8479d3113d250576ce05b7ac92f/src/Yocmen/HtmlMinify/HtmlMinifyCompiler.php#L73)?

Needed for:

```
<!-- googleoff: index -->
Non-SEO text here
<!-- googleon: index -->
```

**Comment by yocmen** [comment]
can you create a pull request?
