### ISSUE TITLE
App environment support

### ISSUE THREAD

**Issue by gstvr** [yocmen/html-minify#4]
Hello!
This is nice and useful Laravel package, but there's one missing thing.

You should create environment support. For example, in config file add attribute 'production'. If it's set to true, then minify HTML only on production environment.

When using package on local environment, it is a bit jumpy, because I can't debug if something is wrong, etc. When I want to deploy my app on environment server, sometimes I even forget to re-enable this functionality in config, so it causes slower app load.

**Comment by yocmen** [comment]
in the config u can do some like 

`'enabled' => !env('APP_DEBUG'),`
