### ISSUE TITLE
Undefined Method

### ISSUE THREAD

**Issue by drizki** [yocmen/html-minify#5]
I get this error:

FatalThrowableError in HtmlMinifyCompiler.php line 21:
Call to undefined method Yocmen\HtmlMinify\HtmlMinifyCompiler::setRawTags()

However, if I comment these line:

```
$this->setRawTags(
    $this->_config['blade']['rawTags'][0],
    $this->_config['blade']['rawTags'][1]
);
$this->setContentTags(
    $this->_config['blade']['contentTags'][0],
    $this->_config['blade']['contentTags'][1]
);

$this->setEscapedContentTags(
    $this->_config['blade']['escapedContentTags'][0],
    $this->_config['blade']['escapedContentTags'][1]
);
```

It works. Any idea?

I'm using Laravel 5.4.

**Comment by mezhevikin** [comment]
I have same problem

**Comment by yocmen** [comment]
Maybe in L 5.4 they remove the function 'setRawTags' from the blade compiler, thats why dont work in L5.4, i will see more details about this, but is hard for me right now, im focus in L5.1 projects.

**Comment by mezhevikin** [comment]
@yocmen Thank you for the response.

@drizki You can use [this](https://github.com/nckg/laravel-minify-html) lib for laravel 5.4 right now.

**Comment by drizki** [comment]
Thank you @yocmen. Do you have any plan on updating the package to support L5.4?

And thank you @mezhevikin for your recommendation. I'll check that one out.

**Comment by yocmen** [comment]
done!, new branch added for L 5.4
