### ISSUE TITLE
Laravel 5.4 ERROR: Call to undefined method Yocmen\HtmlMinify\HtmlMinifyCompiler::setRawTags()

### ISSUE THREAD

**Issue by waiylkarim** [yocmen/html-minify#7]
I've just installed the package, once I refreshed my view it threw the following error:

```
(1/1) FatalThrowableErrorCall to undefined method Yocmen\HtmlMinify\HtmlMinifyCompiler::setRawTags()
--
in HtmlMinifyCompiler.php line 21

....

```

**Comment by yocmen** [comment]
Sorry this packege was forket to be compatible with Laravel 5.1, i cant test it on L5.4 but this way is no longer optimal, u can try like this with GULP, is a better way to minify your assets https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying
